# Generated by Django 4.2.1 on 2023-05-17 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_comments", "0004_add_object_pk_is_removed_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomComment",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_comments.comment",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ("submit_date",),
                "permissions": [("can_moderate", "Can moderate comments")],
                "abstract": False,
            },
            bases=("django_comments.comment",),
        ),
    ]
